sudo: required #super-user permissions
services:
    - docker
before_install: #what to do before run our tests
    - docker build -t kreekeris/docker-demo -f Dockerfile.dev .

script:
    - docker run -e CI=true kreekeris/docker-demo npm run test #npm run tests command

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    name: "docker-demo"
    env: "DockerDemo-env-1"
    bucket_name: "elasticbeanstalk-us-east-2-938022256753"
    bucket_path: "docker-demo"
    on:
        branch: main
    access_key_id: $access_key
    secret_access_key: $secret_key

